server:
  port: 8101

spring:
  application:
    name: ascklrt-payment-server
  cloud:
    # nacos配置
    nacos:
      server-addr: http://127.0.0.1:8010
      # 注册
      discovery:
        server-addr: http://127.0.0.1:8010


dubbo:
  scan:
    base-packages: com.ascklrt.payment
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1

logging:
  config: classpath:log4j2-spring.xml